### ISSUE TITLE
issues with the ecoli demo

### ISSUE THREAD

**Issue by StefanoLonardi** [fxia22/HINGE#50]
I was able to compile and install the tool. When I tried to run the demo on ecoli I was able to run everything OK until this point:

```
stelo@H4:~/HINGE/data$ mkdir log
stelo@H4:~/HINGE/data$ Reads_filter --db ecoli --las ecoli.las -x ecoli --config ~/HINGE/utils/nominal.ini
[2016-07-14 14:06:57.906] [log] [info] Reads filtering
[2016-07-14 14:06:57.906] [log] [info] name of db: ecoli, name of .las file ecoli.las
[2016-07-14 14:06:57.906] [log] [info] name of fasta: , name of .paf file
[2016-07-14 14:06:57.906] [log] [info] Parameters passed in
[filter]
length_threshold = 1000;
quality_threshold = 0.23;
n_iter = 3; // filter iteration
aln_threshold = 1000;
min_cov = 5;
cut_off = 300;
theta = 300;
use_qv = true;
[running]
n_proc = 12;
[draft]
min_cov = 10;
trim = 200;
edge_safe = 100;
tspace = 900;
step = 50;
[consensus]
min_length = 4000;
trim_end = 200;
best_n = 1;
quality_threshold = 0.23;

[layout]
hinge_slack = 1000
min_connected_component_size = 8
[2016-07-14 14:06:57.910] [log] [info] Load alignments from ecoli.las
[2016-07-14 14:06:57.910] [log] [info] # Alignments: 15491688
[2016-07-14 14:06:57.910] [log] [info] # Reads: 82590
[2016-07-14 14:07:07.139] [log] [info] Input data finished
[2016-07-14 14:07:07.198] [log] [info] No debug restrictions.
[2016-07-14 14:07:07.247] [log] [info] use_qv_mask set to true
[2016-07-14 14:07:07.247] [log] [info] use_qv_mask set to true
[2016-07-14 14:07:07.247] [log] [info] number processes set to 12
[2016-07-14 14:07:07.247] [log] [info] LENGTH_THRESHOLD = 1000
[2016-07-14 14:07:07.247] [log] [info] QUALITY_THRESHOLD = 0.23
[2016-07-14 14:07:07.247] [log] [info] N_ITER = 3
[2016-07-14 14:07:07.247] [log] [info] ALN_THRESHOLD = 1000
[2016-07-14 14:07:07.247] [log] [info] MIN_COV = 5
[2016-07-14 14:07:07.247] [log] [info] CUT_OFF = 300
[2016-07-14 14:07:07.247] [log] [info] THETA = 300
[2016-07-14 14:07:07.247] [log] [info] EST_COV = 0
[2016-07-14 14:07:07.247] [log] [info] reso = 40
[2016-07-14 14:07:07.247] [log] [info] use_coverage_mask = true
[2016-07-14 14:07:07.247] [log] [info] COVERAGE_FRACTION = 3
[2016-07-14 14:07:07.247] [log] [info] MIN_REPEAT_ANNOTATION_THRESHOLD = 10
[2016-07-14 14:07:07.247] [log] [info] MAX_REPEAT_ANNOTATION_THRESHOLD = 20
[2016-07-14 14:07:07.247] [log] [info] REPEAT_ANNOTATION_GAP_THRESHOLD = 300
[2016-07-14 14:07:07.247] [log] [info] NO_HINGE_REGION = 500
[2016-07-14 14:07:07.247] [log] [info] HINGE_MIN_SUPPORT = 7
[2016-07-14 14:07:07.247] [log] [info] HINGE_BIN_PILEUP_THRESHOLD = 7
[2016-07-14 14:07:07.247] [log] [info] HINGE_READ_UNBRIDGED_THRESHOLD = 6
[2016-07-14 14:07:07.247] [log] [info] HINGE_BIN_LENGTH = 200
[2016-07-14 14:07:07.247] [log] [info] HINGE_TOLERANCE_LENGTH = 100
Segmentation fault (core dumped)
```
File `log_2016-07-14_14-06.txt` in the directory log is empty

**Comment by fxia22** [comment]
Hi @StefanoLonardi:

This problem is because your .las file contains duplicated records, 

Make sure you run `rm ecoli.*.ecoli.*.las` before running `LAmerge ecoli.las ecoli.*.las`

In the log, the number of alignements should be 7745844 rather than 15491688.

Best,
Fei

**Comment by govinda-kamath** [comment]
Hi Stefano,

The problem seems to be that the regexp is merging some intermediate las files as well. In addition to Fei's suggestion, using the following LAmerge may be safer

``` LAmerge ecoli.las ecoli.+([[:digit:]]).las```

We'll update the Readme to reflect this.

Thanks,
Govinda.

**Comment by StefanoLonardi** [comment]
thank you to both, that was indeed the problem.

Stefano

**Comment by StefanoLonardi** [comment]
```
stelo@H4:~/HINGE/data$ pruning_and_clipping.py ecoli.edges.hinges ecoli.hinge.list demo
Traceback (most recent call last):
  File "/home/stelo/HINGE/scripts/pruning_and_clipping.py", line 10, in <module>
    import ujson
ImportError: No module named ujson
```

In your software dependencies you also need ujson for python

**Comment by StefanoLonardi** [comment]
and colormap

```
stelo@H4:~/HINGE/data$ pruning_and_clipping.py ecoli.edges.hinges ecoli.hinge.list demo
Traceback (most recent call last):
  File "/home/stelo/HINGE/scripts/pruning_and_clipping.py", line 11, in <module>
    from colormap import rgb2hex
ImportError: No module named colormap
```

**Comment by StefanoLonardi** [comment]
and easydev.tools :)

stelo@H4:~/HINGE/data$ pruning_and_clipping.py ecoli.edges.hinges ecoli.hinge.list demo
Traceback (most recent call last):
  File "/home/stelo/HINGE/scripts/pruning_and_clipping.py", line 11, in <module>
    from colormap import rgb2hex
  File "/usr/local/lib/python2.7/dist-packages/colormap/__init__.py", line 32, in <module>
    from . import colors
  File "/usr/local/lib/python2.7/dist-packages/colormap/colors.py", line 26, in <module>
    from easydev.tools import check_param_in_list, swapdict, check_range
ImportError: No module named easydev.tools

**Comment by govinda-kamath** [comment]
Thanks a lot. Added to the Readme. We'll set up a python environment which can be loaded.

**Comment by StefanoLonardi** [comment]
The script run.sh in the demo directory finished successfully, and here is the list of files. Is the assembly in file `ecoli.consensus.fasta` which contains four contigs? Why is the total size 9Mbp, when the genome is ~4.6Mb?

```
-rw-rw-r--  1 stelo stelo   2307957 Jul 15 12:07 .draft.bps
-rw-rw-r--  1 stelo stelo        54 Jul 15 12:07 draft.db
-rw-rw-r--  1 stelo stelo   9463766 Jul 15 12:09 draft.ecoli.1.las
-rw-rw-r--  1 stelo stelo   9154008 Jul 15 12:09 draft.ecoli.2.las
-rw-rw-r--  1 stelo stelo   1722526 Jul 15 12:09 draft.ecoli.3.las
-rw-rw-r--  1 stelo stelo  20340276 Jul 15 13:13 draft.ecoli.las
-rw-rw-r--  1 stelo stelo       272 Jul 15 12:07 .draft.idx
-rw-rw-r--  1 stelo stelo       142 Jul 15 12:07 draft_map.txt
-rw-rw-r--  1 stelo stelo 463094118 Jul 15 09:46 ecoli.1.las
-rw-rw-r--  1 stelo stelo 449776616 Jul 15 09:46 ecoli.2.las
-rw-rw-r--  1 stelo stelo  84334534 Jul 15 09:46 ecoli.3.las
-rw-rw-r--  1 stelo stelo 109278679 Jul 15 09:15 .ecoli.bps
-rw-rw-r--  1 stelo stelo   9292812 Jul 15 13:18 ecoli.consensus.fasta
-rw-rw-r--  1 stelo stelo  82206248 Jul 15 10:02 ecoli.coverage.txt
-rw-rw-r--  1 stelo stelo       195 Jul 15 09:15 ecoli.db
-rw-rw-r--  1 stelo stelo     74679 Jul 15 11:00 ecoli.deadends.txt
-rw-rw-r--  1 stelo stelo       781 Jul 15 11:00 ecoli.debug
-rw-rw-r--  1 stelo stelo   2261858 Jul 15 11:10 ecolidemo.G00.graphml
-rw-rw-r--  1 stelo stelo   2455559 Jul 15 11:10 ecolidemo.G0.graphml
-rw-rw-r--  1 stelo stelo   1942876 Jul 15 11:10 ecolidemo.G1.graphml
-rw-rw-r--  1 stelo stelo    353891 Jul 15 11:10 ecolidemo.G2c.graphml
-rw-rw-r--  1 stelo stelo   1942876 Jul 15 11:10 ecolidemo.G2.graphml
-rw-rw-r--  1 stelo stelo    307175 Jul 15 11:10 ecolidemo.G2s.graphml
-rw-rw-r--  1 stelo stelo    347442 Jul 15 11:10 ecolidemo.Gc.graphml
-rw-rw-r--  1 stelo stelo    300738 Jul 15 11:10 ecolidemo.Gs.graphml
-rw-rw-r--  1 stelo stelo   9231886 Jul 15 12:06 ecoli.draft.fasta
-rw-rw-r--  1 stelo stelo     30874 Jul 15 12:04 ecoli_draft.graphml
-rw-rw-r--  1 stelo stelo   9385767 Jul 15 12:07 ecoli.draft.pb.fasta
-rw-rw-r--  1 stelo stelo    287749 Jul 15 11:00 ecoli.edges.1
-rw-rw-r--  1 stelo stelo    292163 Jul 15 11:00 ecoli.edges.2
-rw-rw-r--  1 stelo stelo    413936 Jul 15 11:00 ecoli.edges.greedy
-rw-rw-r--  1 stelo stelo    413843 Jul 15 11:00 ecoli.edges.hinges
-rw-rw-r--  1 stelo stelo    324453 Jul 15 11:00 ecoli.edges.hinges2
-rw-rw-r--  1 stelo stelo    152555 Jul 15 12:04 ecoli.edges.list
-rw-rw-r--  1 stelo stelo       563 Jul 15 11:00 ecoli.edges.skipped
-rw-rw-r--  1 stelo stelo     19182 Jul 15 11:00 ecoli.hgraph
-rw-rw-r--  1 stelo stelo        39 Jul 15 11:00 ecoli.hinge.list
-rw-rw-r--  1 stelo stelo    582536 Jul 15 10:02 ecoli.hinges.txt
-rw-rw-r--  1 stelo stelo   3303712 Jul 15 09:15 .ecoli.idx
-rw-rw-r--  1 stelo stelo    597831 Jul 15 11:00 ecoli.killed.hinges
-rw-rw-r--  1 stelo stelo 997205244 Jul 15 10:01 ecoli.las
-rw-rw-r--  1 stelo stelo   1197264 Jul 15 10:02 ecoli.mas
-rw-rw-r--  1 stelo stelo    660736 Jul 15 10:02 .ecoli.qual.anno
-rw-rw-r--  1 stelo stelo   4410748 Jul 15 10:02 .ecoli.qual.data
-rw-rw-r--  1 stelo stelo    613347 Jul 15 10:02 ecoli.repeat.txt
-rw-rw-r--  1 stelo stelo    723046 Jul 15 11:00 edges.bkw.backup.txt
-rw-rw-r--  1 stelo stelo    737302 Jul 15 11:00 edges.fwd.backup.txt
-rw-rw-r--  1 stelo stelo    307975 Jul 15 11:00 edges.g_out.txt
drwxrwxr-x  2 stelo stelo      4096 Jul 15 12:04 log/
-rw-rw-r--  1 stelo stelo   8313251 Jul 14 13:46 map.txt
-rw-rw-r--  1 stelo stelo 446206093 Jul 14 13:46 reads.pb.fasta
-rw-rw-r--  1 stelo stelo      1067 Jul 15 13:26 run.sh
```

**Comment by StefanoLonardi** [comment]
I just noticed that run.sh does not have the last line in the readme
`get_consensus_gfa.py <working directory> ecoli ecoli<identifier-of-run>.G2.graphml ecoli.consensus.fasta`
what would this line be for the ecoli example?

**Comment by fxia22** [comment]
@StefanoLonardi It should be `get_consensus_gfa.py $PWD ecoli ecoldemo.G2.graphml ecoli.consensus.fasta` Sorry for the inconvenience.

**Comment by StefanoLonardi** [comment]
Thanks. I have run `get_consensus_gfa.py $PWD ecoli ecolidemo.G2.graphml ecoli.consensus.fasta`, and obtained `ecoli_consensus.gfa`. The size of this latter file is 9292873, which about twice the genome size of E.coli. Is this what we are expecting for this demo run?

**Comment by govinda-kamath** [comment]
Hi Stefano,

That is because we output both the strand and its reverse complement. Hence what you see is around twice the size of the _E. coli_ genome. We think that this representation helps especially if there are some unbridged inverted repeats. 

The bandage visualisation of the assembly is below.

<img width="319" alt="screen shot 2016-07-16 at 10 09 10 am" src="https://cloud.githubusercontent.com/assets/7320464/16896081/b5216cba-4b3d-11e6-97d7-9b766eb16b3f.png">

Thanks,
Govinda.
